(* test/test_transport_tcp.ml

   Permanent regression coverage for [Riptide_transport.Tcp], the real-socket implementation of
   [Transport_intf.S]. These tests exercise real loopback TCP via [Eio_main.run] (NOT
   [Eio_mock.Backend] -- there is no mock socket layer to substitute here; the whole point is to
   prove the real wire behavior).

   {b What these tests do not cover, permanently.} An earlier round of work on [tcp.ml] fixed a
   family of crash bugs -- a write to a peer that had already died, and a corrupt/oversized frame,
   each behaving differently depending on whether the connection had been dialed or accepted --
   whose defining symptom was that they killed the whole OS process, not just one connection (see
   [tcp.ml]'s doc comment on [run_connection] for the mechanism and the fix). Nothing below
   regression-tests that class of bug, and nothing in this file structurally can: observing
   "process A survived process B's death" requires two real OS processes, and this suite runs a
   whole mesh inside one. A failure of that kind would take the test runner itself down rather
   than fail an assertion. So treat a green run here as evidence about the framing, routing and
   delivery properties listed below, and {b not} as evidence that the process-crash-on-dead-peer
   scenarios are still fixed -- those were verified with throwaway multi-process harnesses at the
   time, and re-verifying them needs the same kind of harness again. Closing this gap properly
   would mean a multi-process integration-test mechanism this repo does not yet have.

   What this file does lock in, permanently, is the three properties that would otherwise have no
   lasting test:
   - a real multi-peer mesh actually delivers messages correctly, in both directions, on every
     pairwise connection;
   - length-prefixed framing is byte-exact even when payload content itself contains bytes that
     look like framing metadata -- two back-to-back sends over one connection arrive as two
     distinct, unmodified messages, never merged or split;
   - each peer's [receive] only ever surfaces messages actually sent [~to_] it, with no
     cross-peer misattribution, even under concurrent multi-connection traffic;
   - [Tcp.create] does not return until every SPECIFIC expected peer id is connected, rather than
     merely that many connections existing (see that test's own comment);
   - the dial side's own TLS handshake (inside [connect_to]) is bounded by
     [tls_handshake_timeout], the same as the accept side's, rather than able to hang [Tcp.create]
     forever against a peer that accepts the TCP connection and then never speaks TLS back (see
     [test_dial_side_tls_handshake_has_a_bounded_timeout] below for how this is timed without
     actually waiting out the real ~10s).

   One further failure path is not covered here, for reasons of mechanism rather than oversight,
   and was instead verified with a throwaway harness: the listener surviving a transient
   [accept(2)] error needs the process's file-descriptor budget deliberately exhausted, which
   would break the test runner itself long before it reached an assertion. The {e accept} side's
   own bounded waits (the TLS handshake and the handshake-preamble read, both ~10s) are similarly
   not exercised here on a real clock, for the reason above -- ~10s eats most of this suite's own
   15s-per-test watchdog budget. The {e dial} side's equivalent new timeout, added in this file
   alongside the fix, sidesteps that by racing the real handshake against a virtual
   [Eio_mock.Clock] instead of the real one, so it does not have this problem and is covered.

   Port choice: distinct, non-overlapping port ranges per test (19301-19303, 19311-19312,
   19321-19323, 19331-19333, 19341-19342, 19351, 19352, 19353, 19361-19362, 19371-19372) so a
   re-run or a future added test in this file can't collide even if an earlier
   test's sockets are still winding down -- [Tcp.create] itself passes [~reuse_addr:true] to
   [Eio.Net.listen], but distinct ports sidestep the question entirely rather than relying on
   that. [Tcp.create] does not expose its internal listening socket, so there is no way to ask it
   for an OS-assigned ephemeral (port 0) address from outside; fixed, spread-out ports are the
   only option here. *)

open Riptide_transport

(* -- Mutual-TLS test material --------------------------------------------------------------

   [Tcp] is unconditionally mutually-authenticated: every test in this file therefore has to hand
   [Tcp.create] a real X.509 identity, and every one of them is consequently also an end-to-end
   proof that the mTLS handshake succeeded -- a mesh that failed to handshake delivers no bytes at
   all, so the delivery/framing/attribution assertions below cannot pass without it.

   Two entirely unrelated certificate authorities exist here, both generated by Task 7's own
   [Riptide_pki.Ca] (no PEM round-trip, no fixture files):
   - [cluster_ca] issues every legitimate peer's leaf, and is the trust anchor every legitimate
     peer is configured with;
   - [foreign_ca] issues nothing any legitimate peer trusts. It exists solely so the negative
     cases below can present a certificate that is perfectly well-formed and validly signed --
     just not by an authority this cluster has any reason to accept. That is the distinction the
     negative tests are actually about: rejection must come from the trust decision, not from
     handing the peer garbage bytes it would have rejected for some unrelated parsing reason. *)

let () = Mirage_crypto_rng_unix.use_default ()

let cluster_ca = Riptide_pki.Ca.generate_root ~common_name:"riptide-tcp-test-cluster-root"
let foreign_ca = Riptide_pki.Ca.generate_root ~common_name:"riptide-tcp-test-foreign-root"

let leaf_of (ca : Riptide_pki.Ca.t) name = Riptide_pki.Ca.sign_leaf ca ~common_name:name ~valid_days:1

(* A fully self-consistent identity: a leaf signed by [ca], trusting [ca]. *)
let identity_of (ca : Riptide_pki.Ca.t) name =
  let cert, priv_key = leaf_of ca name in
  Tls_identity.create ~trust_anchor:ca.Riptide_pki.Ca.cert ~cert ~priv_key

let peer_identity id = identity_of cluster_ca (Printf.sprintf "peer-%d.riptide.test" id)

(* [Tcp.t] has no close/shutdown operation (see tcp.mli's "No shutdown path" section): its
   listener's accept loop and every connection's reader/writer fibers are forked onto the [sw]
   passed to [Tcp.create] and run for as long as that switch is alive. [Eio.Switch.run]'s own
   contract ([switch.mli]: "waits for all fibers registered with the switch to finish, and then
   releases all attached resources") means simply falling off the end of a test body inside a bare
   [Eio.Switch.run] would block [Switch.run] forever waiting for that never-ending accept loop --
   confirmed live while developing this file (the very first draft hung every test until the
   suite's own 5s SIGALRM watchdog fired). [Test_mesh_torn_down] is this file's use of the
   "explicit [Eio.Switch.fail]/cancellation" escape hatch tcp.mli's own doc names as the only way
   to force such a switch to finish from the outside. *)
exception Test_mesh_torn_down

(* Brings up one [Tcp.t] per entry in [peer_specs], all concurrently (every entry's dial loop
   needs the others' listeners to already be up, or coming up within its own retry budget -- see
   [Tcp.create]'s docs), runs [body] against the resulting handles (keyed by peer id), then force-
   tears the mesh down so this function returns instead of hanging -- see [Test_mesh_torn_down]
   above for why that's necessary. *)
let with_mesh peer_specs body =
  Eio_main.run @@ fun env ->
  let net = Eio.Stdenv.net env in
  let clock = Eio.Stdenv.clock env in
  try
    Eio.Switch.run (fun sw ->
        let handles = Hashtbl.create (List.length peer_specs) in
        Eio.Fiber.all
          (List.map
             (fun (my_id, _, _) ->
               fun () ->
                 let t =
                   Tcp.create ~sw ~net ~clock ~my_id ~peers:peer_specs ~tls:(peer_identity my_id)
                 in
                 Hashtbl.replace handles my_id t)
             peer_specs);
        body handles;
        Eio.Switch.fail sw Test_mesh_torn_down)
  with Test_mesh_torn_down -> ()

(* -- Area 1: real-loopback, multi-peer delivery -- *)

let test_three_peer_mesh_bidirectional_delivery () =
  let peer_specs = [ (1, "127.0.0.1", 19301); (2, "127.0.0.1", 19302); (3, "127.0.0.1", 19303) ] in
  with_mesh peer_specs (fun handles ->
      let get id = Hashtbl.find handles id in
      (* Every unordered pair gets exercised in both directions, covering all three physical
         connections this mesh forms (1-2, 1-3, 2-3, per the lower-dials-higher topology documented
         in tcp.mli) without any way for this test to observe connection identity directly -- the
         observable property is "every pairwise send/receive round-trips correctly, in order,
         verbatim", which is what actually matters at this module's public interface. *)
      let pairs = [ (1, 2); (2, 1); (1, 3); (3, 1); (2, 3); (3, 2) ] in
      List.iter
        (fun (from_, to_) ->
          let msgs = List.init 3 (fun i -> Printf.sprintf "peer%d->peer%d#%d" from_ to_ i) in
          List.iter (fun m -> Tcp.send (get from_) ~to_ m) msgs;
          List.iter
            (fun expected ->
              Alcotest.(check string)
                (Printf.sprintf "peer %d receives peer %d's message, verbatim and in order" to_
                   from_)
                expected (Tcp.receive (get to_)))
            msgs)
        pairs)

(* -- Area 2: framing-boundary correctness -- *)

let test_framing_boundary_back_to_back_messages_stay_distinct () =
  let peer_specs = [ (1, "127.0.0.1", 19311); (2, "127.0.0.1", 19312) ] in
  with_mesh peer_specs (fun handles ->
      let a = Hashtbl.find handles 1 and b = Hashtbl.find handles 2 in
      (* Both payloads deliberately embed bytes that look exactly like this module's own 8-byte
         big-endian length-prefix framing (see tcp.ml's [write_frame]/[read_frame]) followed by
         content that would, if a receiver ever mistakenly scanned payload bytes for a nested
         prefix/delimiter instead of trusting only the real out-of-band prefix that precedes each
         frame, look like a second, smaller message hiding inside the first. A byte-exact,
         length-prefix-only reader treats all of this as fully opaque payload content. *)
      let msg1 = "\x00\x00\x00\x00\x00\x00\x00\x05hello-this-is-actually-all-of-msg1-not-just-hello" in
      let msg2 = "\x00\x00\x00\x00\x00\x00\x00\x04ABCD-and-this-is-all-of-msg2-too" in
      Tcp.send a ~to_:2 msg1;
      Tcp.send a ~to_:2 msg2;
      let r1 = Tcp.receive b in
      let r2 = Tcp.receive b in
      Alcotest.(check string)
        "first back-to-back send is received whole and unmodified, not merged with the second" msg1
        r1;
      Alcotest.(check string)
        "second back-to-back send is received whole and unmodified, not merged with or split off \
         the first"
        msg2 r2;
      Alcotest.(check bool) "no leftover/duplicated bytes beyond the two expected messages" true
        (Tcp.receive_nonblocking b = None))

(* -- Area 3: handshake / peer-attribution correctness under concurrent traffic -- *)

let test_no_cross_peer_misattribution_under_concurrent_traffic () =
  let peer_specs = [ (1, "127.0.0.1", 19321); (2, "127.0.0.1", 19322); (3, "127.0.0.1", 19323) ] in
  with_mesh peer_specs (fun handles ->
      let ids = [ 1; 2; 3 ] in
      let seqs = [ 0; 1; 2 ] in
      let tag from_ to_ seq = Printf.sprintf "msg-from%d-to%d-seq%d" from_ to_ seq in
      let pairs =
        List.concat_map
          (fun from_ -> List.filter_map (fun to_ -> if from_ = to_ then None else Some (from_, to_)) ids)
          ids
      in
      (* [receive]'s own signature carries no sender identity (see transport_intf.ml) -- the only
         way this layer can prove "peer A only ever sees messages actually sent [~to_:A]" is by
         round-tripping identity through payload content itself, the same way a real caller's
         envelope would. *)
      let expected_for p =
        List.concat_map (fun (from_, to_) -> if to_ = p then List.map (tag from_ to_) seqs else []) pairs
        |> List.sort compare
      in
      let received = Hashtbl.create (List.length ids) in
      (* Fire every sender for every pair, and every receiver's full expected drain, all as fibers
         running concurrently against the same live mesh -- this is what actually stresses
         misattribution: without this, a bug that routed a send meant for peer 3 onto peer 2's
         connection instead could still pass a test that only ever has one connection active at a
         time. *)
      Eio.Fiber.all
        (List.concat_map
           (fun (from_, to_) ->
             List.map (fun seq () -> Tcp.send (Hashtbl.find handles from_) ~to_ (tag from_ to_ seq)) seqs)
           pairs
        @ List.map
            (fun p () ->
              let expected_count = List.length (expected_for p) in
              let msgs = List.init expected_count (fun _ -> Tcp.receive (Hashtbl.find handles p)) in
              Hashtbl.replace received p (List.sort compare msgs))
            ids);
      List.iter
        (fun p ->
          Alcotest.(check (list string))
            (Printf.sprintf
               "peer %d's receive() surfaces exactly the messages sent ~to_ it (and only those), \
                even under concurrent multi-connection traffic"
               p)
            (expected_for p) (Hashtbl.find received p))
        ids)

(* -- Area 4: [create]'s mesh-readiness predicate -- *)

exception Stray_mesh_torn_down

let be8 n =
  let b = Bytes.create 8 in
  Bytes.set_int64_be b 0 (Int64.of_int n);
  Bytes.to_string b

(* [Tcp.create] must not return until it has an outbound path to each SPECIFIC other peer id in
   the membership table -- not merely to that MANY peers. The distinction is observable because
   the per-peer connection table is keyed by the id a handshake preamble claims, and that id is
   trusted rather than checked against the membership table (see tcp.mli's preamble note): any
   accepted connection lands in it, including one claiming an id the cluster has never heard of.

   This test makes the difference decide the outcome. Two stray sockets connect to peer 3's
   listener and claim ids 98 and 99 -- neither in [peer_specs] -- before peers 1 and 2 have even
   started. That is exactly as many connections as peer 3 is waiting for, so a readiness check
   that counted entries would declare the mesh formed and let [create] return with no path to
   either real peer. Peer 3's fiber therefore sends to both real peers the instant its own
   [create] returns, while peers 1 and 2 may still be starting: against a count-based check those
   sends raise [Invalid_argument "no connection to peer 1"], and against a per-id check they
   cannot, because [create] cannot have returned yet. The receives are asserted afterwards, once
   every peer is up, so the assertion proves the messages were also really delivered.

   The strays speak real mTLS, presenting their own leaf certificates issued by the same
   [cluster_ca] every legitimate peer trusts, and write their claimed preamble id {e inside} the
   resulting TLS flow. That is deliberate and load-bearing, not incidental: a stray that failed
   the handshake would never reach peer 3's connection table at all, which would make this test
   quietly vacuous (a count-based readiness check and a per-id one would then agree, and the test
   would pass against both). It is also the honest threat model now that {!Tcp} is mutually
   authenticated -- mTLS proves an incoming connection holds a certificate this cluster's CA
   issued, and nothing more; the preamble id it then claims is still not bound to that
   certificate, exactly as tcp.mli says. These two strays are that residual gap, made
   observable. *)
let test_create_waits_for_the_specific_expected_peers () =
  let peer_specs = [ (1, "127.0.0.1", 19331); (2, "127.0.0.1", 19332); (3, "127.0.0.1", 19333) ] in
  let stray_addr : Eio.Net.Sockaddr.stream = `Tcp (Eio.Net.Ipaddr.V4.loopback, 19333) in
  let msg = "sent-the-instant-create-returned" in
  Eio_main.run @@ fun env ->
  let net = Eio.Stdenv.net env in
  let clock = Eio.Stdenv.clock env in
  try
    Eio.Switch.run (fun sw ->
        let handles = Hashtbl.create (List.length peer_specs) in
        Eio.Fiber.all
          ((fun () ->
             (* Let peer 3's listener bind first (it starts without any delay, below), then park
                two connections on it claiming ids outside the membership table entirely. *)
             Eio.Time.sleep clock 0.1;
             List.iter
               (fun claimed_id ->
                 let flow = Eio.Net.connect ~sw net stray_addr in
                 let tls =
                   Tls_eio.client_of_flow
                     (Tls_identity.client_config
                        (identity_of cluster_ca
                           (Printf.sprintf "stray-%d.riptide.test" claimed_id)))
                     flow
                 in
                 Eio.Flow.copy_string (be8 claimed_id) tls)
               [ 98; 99 ])
          :: List.map
               (fun (my_id, _, _) () ->
                 (* Peers 1 and 2 start late deliberately, so that the strays are the only thing
                    in peer 3's connection table when a count-based check would have fired. *)
                 if my_id <> 3 then Eio.Time.sleep clock 0.5;
                 let t =
                   Tcp.create ~sw ~net ~clock ~my_id ~peers:peer_specs ~tls:(peer_identity my_id)
                 in
                 Hashtbl.replace handles my_id t;
                 if my_id = 3 then List.iter (fun to_ -> Tcp.send t ~to_ msg) [ 1; 2 ])
               peer_specs);
        List.iter
          (fun id ->
            Alcotest.(check string)
              (Printf.sprintf
                 "peer %d receives what peer 3 sent the instant peer 3's own create returned" id)
              msg
              (Tcp.receive (Hashtbl.find handles id)))
          [ 1; 2 ];
        Eio.Switch.fail sw Stray_mesh_torn_down)
  with Stray_mesh_torn_down -> ()

(* -- Area 5: mutual TLS ---------------------------------------------------------------------

   Two different levels of evidence are needed here, and neither substitutes for the other.

   (a) {b At the wire.} That the mTLS handshake happens {e at all} and that nothing this module
       sends afterwards bypasses it. Proved by [test_first_bytes_on_the_wire_are_a_tls_handshake]
       below, which sniffs the raw socket directly: the very first bytes a dialing peer puts on
       it must be a TLS record, never this module's own plaintext 8-byte handshake preamble.

   (b) {b At the trust decision.} That {e both} ends actually verify the other's certificate. The
       client half is visible end-to-end through [Tcp.create] itself (a dialer refuses to finish
       connecting to a server whose certificate it cannot chain to its own CA). The server half
       -- the one that is silently absent if [Tls.Config.server]'s own optional [?authenticator]
       is left unset, in which case the server happily accepts any client certificate, or none --
       is not observable through [Tcp]'s public surface on any useful timescale: a rejected client
       simply never appears in the server's connection table, and the only externally visible
       consequence is that [Tcp.create]'s ~20s mesh-formation budget eventually expires, which is
       both far too slow for this suite and far too weak an assertion (it would pass just as
       happily if the client had never dialed at all). So those cases drive [Tls_eio] directly,
       through the {e same} [Tls_identity.server_config] value [Tcp] itself uses -- the production
       server configuration is the actual subject under test, and the client is the adversary.

   The adversary's own [Tls.Config.client] values are built by hand here rather than through
   [Tls_identity], on purpose: an attacker does not use our helper, and hand-building is also the
   only way to express the two configurations that matter (a client that trusts our CA while
   presenting a certificate from another one, and a client presenting no certificate at all). *)

let tls_authenticator_for (ca : Riptide_pki.Ca.t) =
  X509.Authenticator.chain_of_trust
    ~time:(fun () -> Some (Ptime_clock.now ()))
    [ ca.Riptide_pki.Ca.cert ]

let adversary_client_config ?certificates () =
  match
    Tls.Config.client ~authenticator:(tls_authenticator_for cluster_ca)
      ?certificates
      ~version:(`TLS_1_3, `TLS_1_3) ()
  with
  | Ok c -> c
  | Error (`Msg m) -> Alcotest.failf "test setup: could not build adversary client config: %s" m

(* Runs exactly one TLS handshake over one real loopback TCP connection. The server side always
   uses [Tls_identity.server_config server_identity] -- byte for byte the configuration
   [Tcp.create] installs for its own listener -- and then reads four bytes of application data
   through the resulting TLS flow. The client side is whatever [client_config] the caller passes.

   Returns the {e server's} view, classified: this is the side whose trust decision is under test,
   and reading its outcome directly is what stops these tests from degenerating into "some branch
   of some code ran". Because the only thing that differs between the positive control and each
   negative case below is the client's certificate, "accepted" vs "rejected-by-tls" is a
   difference the certificate alone produced. *)
let server_side_of_one_handshake ~port ~server_identity ~client_config =
  let outcome = ref (Error End_of_file) in
  let addr : Eio.Net.Sockaddr.stream = `Tcp (Eio.Net.Ipaddr.V4.loopback, port) in
  Eio_main.run (fun env ->
      let net = Eio.Stdenv.net env in
      Eio.Switch.run (fun sw ->
          let listener = Eio.Net.listen ~reuse_addr:true ~backlog:1 ~sw net addr in
          Eio.Fiber.both
            (fun () ->
              let flow, _addr = Eio.Net.accept ~sw listener in
              match Tls_eio.server_of_flow (Tls_identity.server_config server_identity) flow with
              | exception exn -> outcome := Error exn
              | tls -> (
                let r = Eio.Buf_read.of_flow tls ~max_size:4096 in
                match Eio.Buf_read.take 4 r with
                | exception exn -> outcome := Error exn
                | got -> outcome := Ok (got, Tls_eio.epoch tls)))
            (fun () ->
              let flow = Eio.Net.connect ~sw net addr in
              (* Every failure the adversary side can hit is expected and irrelevant to the
                 assertion: if the client is the one that rejects, or if it is cut off mid-write by
                 the server's alert, that is fine -- what is being asserted is the server's
                 outcome, recorded above. [Eio.Cancel.Cancelled] is deliberately not caught. *)
              match Tls_eio.client_of_flow client_config flow with
              | exception (Tls_eio.Tls_alert _ | Tls_eio.Tls_failure _ | End_of_file | Eio.Io _) ->
                ()
              | tls -> (
                match Eio.Flow.copy_string "ping" tls with
                | () -> ()
                | exception
                    (Tls_eio.Tls_alert _ | Tls_eio.Tls_failure _ | End_of_file | Eio.Io _) ->
                  ()))));
  !outcome

let classify_server_outcome = function
  | Ok _ -> "accepted"
  | Error (Tls_eio.Tls_failure _) -> "rejected-by-tls"
  | Error (Tls_eio.Tls_alert _) -> "rejected-by-tls"
  | Error exn -> "other-failure: " ^ Printexc.to_string exn

(* The positive control for the two negative cases below, and the explicit end-to-end proof that a
   real mutual handshake between two Task-7-CA-signed identities succeeds and carries application
   bytes. The two epoch assertions are what make it a proof of {e mutual} authentication rather
   than of server-only TLS: the server having a [peer_certificate] at all means the client really
   did present one and it really was verified against the trust anchor. *)
let test_mutual_handshake_between_two_ca_signed_peers_succeeds () =
  let outcome =
    server_side_of_one_handshake ~port:19351 ~server_identity:(peer_identity 1)
      ~client_config:(Tls_identity.client_config (peer_identity 2))
  in
  Alcotest.(check string)
    "a client holding a leaf issued by the cluster CA completes the mutual handshake" "accepted"
    (classify_server_outcome outcome);
  match outcome with
  | Error _ -> Alcotest.fail "unreachable: outcome was classified as accepted"
  | Ok (payload, epoch) ->
    Alcotest.(check string) "application bytes cross the TLS-wrapped flow verbatim" "ping" payload;
    let epoch = match epoch with Ok e -> e | Error () -> Alcotest.fail "no TLS epoch available" in
    Alcotest.(check bool)
      "the server holds the client's verified certificate, i.e. the handshake was MUTUAL" true
      (epoch.Tls.Core.peer_certificate <> None);
    Alcotest.(check bool)
      "the server resolved the client's chain to a trust anchor" true
      (epoch.Tls.Core.trust_anchor <> None);
    (* The version pin is real, not just written down: both ends are configured TLS 1.3-only, so
       a future edit that widened the range to admit older versions (and with them
       downgrade negotiation) would have to change this assertion too. *)
    Alcotest.(check string) "the session negotiated the pinned protocol version"
      (Fmt.to_to_string Tls.Core.pp_tls_version (snd Tls_identity.protocol_version))
      (Fmt.to_to_string Tls.Core.pp_tls_version epoch.Tls.Core.protocol_version)

(* {b Negative case 1, the Review Focus case.} A client that trusts this cluster's CA (so it has
   no objection of its own to raise, and the handshake really does get as far as the server's
   trust decision) but presents a leaf issued by an entirely unrelated CA. The server must reject
   it. If [Tls.Config.server]'s own [?authenticator] were left unset -- the single easiest thing
   to miss when wiring mTLS, since the client side's [authenticator] is mandatory and the server
   side's is not -- this test would classify as "accepted", because the server would take the
   foreign certificate without looking at it. *)
let test_server_rejects_a_client_certificate_from_an_unrelated_ca () =
  let rogue_cert, rogue_key = leaf_of foreign_ca "rogue.riptide.test" in
  let outcome =
    server_side_of_one_handshake ~port:19352 ~server_identity:(peer_identity 1)
      ~client_config:(adversary_client_config ~certificates:(`Single ([ rogue_cert ], rogue_key)) ())
  in
  Alcotest.(check string)
    "a client whose leaf is signed by an unrelated CA is rejected at the handshake"
    "rejected-by-tls" (classify_server_outcome outcome)

(* {b Negative case 2.} The same server, same port topology, same everything -- except the client
   presents no certificate at all. A server whose [?authenticator] is unset does not even ask for
   one, and this connection would be established as ordinary one-way TLS. It must be rejected. *)
let test_server_rejects_a_client_presenting_no_certificate () =
  let outcome =
    server_side_of_one_handshake ~port:19353 ~server_identity:(peer_identity 1)
      ~client_config:(adversary_client_config ())
  in
  Alcotest.(check string) "a client presenting no certificate is rejected at the handshake"
    "rejected-by-tls" (classify_server_outcome outcome)

(* The other half of mutual authentication, asserted end-to-end through [Tcp.create]'s own real
   dialing path rather than against [Tls_eio] directly: peer 1 trusts [cluster_ca], peer 2 is a
   complete, internally-consistent replica of some {e other} cluster (its own CA, its own leaf).
   Peer 1 must refuse to complete the connection, and must say why -- [Tcp.create] surfacing this
   as a bare dial timeout, or (worse) proceeding, would both be failures here. *)
let test_dialer_rejects_a_server_certificate_from_an_unrelated_ca () =
  let peer_specs = [ (1, "127.0.0.1", 19361); (2, "127.0.0.1", 19362) ] in
  let identity_for id = if id = 1 then peer_identity 1 else identity_of foreign_ca "impostor.riptide.test" in
  let failure = ref None in
  (try
     Eio_main.run (fun env ->
         let net = Eio.Stdenv.net env in
         let clock = Eio.Stdenv.clock env in
         Eio.Switch.run (fun sw ->
             Eio.Fiber.all
               (List.map
                  (fun (my_id, _, _) () ->
                    ignore
                      (Tcp.create ~sw ~net ~clock ~my_id ~peers:peer_specs
                         ~tls:(identity_for my_id)))
                  peer_specs)))
   with Failure msg -> failure := Some msg);
  let msg =
    match !failure with
    | Some msg -> msg
    | None ->
      Alcotest.fail
        "Tcp.create completed against a peer presenting a certificate from an unrelated CA -- the \
         dialing side's authenticator did not reject it"
  in
  let contains needle haystack =
    let nl = String.length needle and hl = String.length haystack in
    let rec go i = i + nl <= hl && (String.sub haystack i nl = needle || go (i + 1)) in
    go 0
  in
  Alcotest.(check bool)
    (Printf.sprintf
       "the failure names the TLS handshake with peer 2 as the cause, not a generic dial timeout \
        (got: %s)"
       msg)
    true
    (contains "TLS handshake" msg && contains "peer 2" msg)

(* [Tls_identity.create]'s own two startup checks. Both exist to turn a silent misconfiguration
   into a loud one at boot instead of an opaque handshake failure later, so both need a test that
   proves the check fires -- otherwise the checks are exactly the kind of prose-shaped claim that
   no code exercises. *)

let expect_tls_config_error what f =
  match f () with
  | (_ : Tls_identity.t) -> Alcotest.failf "Tls_identity.create accepted %s" what
  | exception Tls_identity.Tls_config_error _ -> ()

let test_identity_rejects_a_key_that_does_not_match_its_certificate () =
  let cert, _ = leaf_of cluster_ca "matched.riptide.test" in
  let _, other_key = leaf_of cluster_ca "unrelated.riptide.test" in
  expect_tls_config_error "a certificate paired with an unrelated private key" (fun () ->
      Tls_identity.create ~trust_anchor:cluster_ca.Riptide_pki.Ca.cert ~cert ~priv_key:other_key)

let test_identity_rejects_a_certificate_its_trust_anchor_did_not_issue () =
  let cert, priv_key = leaf_of foreign_ca "elsewhere.riptide.test" in
  expect_tls_config_error "its own certificate not chaining to its own trust anchor" (fun () ->
      Tls_identity.create ~trust_anchor:cluster_ca.Riptide_pki.Ca.cert ~cert ~priv_key)

(* Nothing this module puts on the wire may bypass the TLS flow. That is a property no
   application-level round-trip test can distinguish from "TLS was negotiated and then ignored",
   so it is asserted where it is actually observable: on the raw socket.
   A plain TCP listener stands in for peer 2 and reads the first bytes peer 1's dialing path
   writes. Those bytes must be a TLS handshake record, and must specifically {e not} be this
   module's own 8-byte plaintext handshake preamble -- which is exactly what a wiring that
   TLS-wrapped nothing, or that wrapped the flow but kept writing the preamble to the raw socket
   underneath it, would produce. *)
exception Wire_probe_done

let test_first_bytes_on_the_wire_are_a_tls_handshake () =
  let peer_specs = [ (1, "127.0.0.1", 19341); (2, "127.0.0.1", 19342) ] in
  let first_bytes = ref "" in
  Eio_main.run @@ fun env ->
  let net = Eio.Stdenv.net env in
  let clock = Eio.Stdenv.clock env in
  (try
     Eio.Switch.run (fun sw ->
         let listener =
           Eio.Net.listen ~reuse_addr:true ~backlog:1 ~sw net
             (`Tcp (Eio.Net.Ipaddr.V4.loopback, 19342))
         in
         Eio.Fiber.both
           (fun () ->
             let flow, _addr = Eio.Net.accept ~sw listener in
             let r = Eio.Buf_read.of_flow flow ~max_size:4096 in
             first_bytes := Eio.Buf_read.take 8 r;
             (* Peer 1 is now blocked waiting for a ServerHello that is never coming; tearing the
                switch down is how this test ends rather than sitting out peer 1's dial budget. *)
             Eio.Switch.fail sw Wire_probe_done)
           (fun () ->
             ignore (Tcp.create ~sw ~net ~clock ~my_id:1 ~peers:peer_specs ~tls:(peer_identity 1))))
   with Wire_probe_done -> ());
  let observed = !first_bytes in
  Alcotest.(check int) "the probe actually captured the dialer's first bytes" 8
    (String.length observed);
  Alcotest.(check bool)
    (Printf.sprintf
       "the dialer's first wire bytes are a TLS handshake record (0x16), not plaintext (got %S)"
       observed)
    true
    (String.length observed > 0 && observed.[0] = '\x16');
  Alcotest.(check bool)
    "...and specifically not this module's own 8-byte plaintext handshake preamble" false
    (observed = be8 1)

(* -- Area 6: dial-side TLS handshake timeout -----------------------------------------------

   Regression test for the finding fixed in this round: [connect_to]'s call to
   [Tls_eio.client_of_flow] used to have no timeout at all, unlike [handle_accepted]'s equivalent
   [server_of_flow] call. A peer that accepts the TCP connection and then never speaks TLS back --
   wedged, mid-restart, or behind a path that silently drops packets after [connect] -- used to
   park [Tcp.create] inside the handshake forever, with no diagnostic, *before*
   [mesh_formation_timeout] ever got a chance to apply. The fix wraps the dial-side handshake in
   the same [Eio.Time.with_timeout clock tls_handshake_timeout] the accept side already used.

   A raw TCP listener again stands in for peer 2 (as in
   [test_first_bytes_on_the_wire_are_a_tls_handshake] above), except this one accepts the
   connection and then holds it open without ever writing a byte, instead of being torn down
   immediately -- exactly the hang scenario the finding describes.

   Waiting out the real [tls_handshake_timeout] (~10s) here, on the suite's real wall clock, would
   eat most of this suite's own 15s-per-test watchdog budget (see this file's header comment) --
   uncomfortably close for a suite that otherwise runs in a couple of seconds. [Tcp.create]'s
   [~clock] argument is a plain [_ Eio.Time.clock], though, so this test hands it an
   [Eio_mock.Clock] instead of the real one -- the same virtual-time mechanism
   [lib/sim/network.ml] already uses to drive [Riptide_sim]'s simulated network deterministically.
   The raw TCP connect and the handshake's own blocked read are still real OS I/O via
   [Eio_main.run]; only the timeout race's notion of elapsed time is virtual, which is what lets
   this test fire the timeout near-instantly and deterministically instead of either sleeping for
   real or racing the assertion against wall-clock flakiness. *)
exception Handshake_timeout_probe_done

let test_dial_side_tls_handshake_has_a_bounded_timeout () =
  let peer_specs = [ (1, "127.0.0.1", 19371); (2, "127.0.0.1", 19372) ] in
  let result = ref None in
  Eio_main.run @@ fun env ->
  let net = Eio.Stdenv.net env in
  let real_clock = Eio.Stdenv.clock env in
  let mock_clock = Eio_mock.Clock.make () in
  let clock_for_tcp : float Eio.Time.clock_ty Eio.Std.r =
    (mock_clock :> float Eio.Time.clock_ty Eio.Std.r)
  in
  (try
     Eio.Switch.run (fun sw ->
         let listener =
           Eio.Net.listen ~reuse_addr:true ~backlog:1 ~sw net
             (`Tcp (Eio.Net.Ipaddr.V4.loopback, 19372))
         in
         Eio.Fiber.both
           (fun () ->
             (* Accept the raw connection -- proving the finding's premise, that the raw TCP
                connect succeeds -- then hold [flow] open and silent. [sw] keeps the fd alive after
                this fiber moves on, so peer 1's dialer genuinely blocks inside
                [Tls_eio.client_of_flow] waiting for a ServerHello that is never coming. Once that
                wait has registered its timeout job on the mock clock, push virtual time past it to
                fire the timeout deterministically rather than waiting out the real ~10s. *)
             let flow, _addr = Eio.Net.accept ~sw listener in
             ignore flow;
             let rec wait_for_timeout_job () =
               match Eio_mock.Clock.advance mock_clock with
               | () -> ()
               | exception Invalid_argument _ ->
                 Eio.Time.sleep real_clock 0.02;
                 wait_for_timeout_job ()
             in
             wait_for_timeout_job ())
           (fun () ->
             (match
                Tcp.create ~sw ~net ~clock:clock_for_tcp ~my_id:1 ~peers:peer_specs
                  ~tls:(peer_identity 1)
              with
             | (_ : Tcp.t) ->
               Alcotest.fail
                 "Tcp.create succeeded despite peer 2 never completing its TLS handshake"
             | exception Failure msg -> result := Some msg);
             Eio.Switch.fail sw Handshake_timeout_probe_done))
   with Handshake_timeout_probe_done -> ());
  let msg =
    match !result with
    | Some msg -> msg
    | None ->
      Alcotest.fail
        "Tcp.create never raised -- the dial-side TLS handshake timeout did not fire"
  in
  let contains needle haystack =
    let nl = String.length needle and hl = String.length haystack in
    let rec go i = i + nl <= hl && (String.sub haystack i nl = needle || go (i + 1)) in
    go 0
  in
  Alcotest.(check bool)
    (Printf.sprintf
       "the failure names the TLS handshake and peer 2 specifically, not a generic dial timeout \
        (got: %s)"
       msg)
    true
    (contains "TLS handshake" msg && contains "peer 2" msg)

let tests =
  [ ("three-peer mesh: bidirectional delivery on every pairwise connection", `Quick,
      test_three_peer_mesh_bidirectional_delivery);
    ("framing boundary: back-to-back sends stay distinct, byte-exact", `Quick,
      test_framing_boundary_back_to_back_messages_stay_distinct);
    ("no cross-peer misattribution under concurrent traffic", `Quick,
      test_no_cross_peer_misattribution_under_concurrent_traffic);
    ("create waits for the specific expected peers, not merely that many connections", `Quick,
      test_create_waits_for_the_specific_expected_peers);
    ("mTLS: a mutual handshake between two CA-signed peers succeeds and carries bytes", `Quick,
      test_mutual_handshake_between_two_ca_signed_peers_succeeds);
    ("mTLS: the server rejects a client certificate signed by an unrelated CA", `Quick,
      test_server_rejects_a_client_certificate_from_an_unrelated_ca);
    ("mTLS: the server rejects a client presenting no certificate at all", `Quick,
      test_server_rejects_a_client_presenting_no_certificate);
    ("mTLS: the dialer rejects a server certificate signed by an unrelated CA", `Quick,
      test_dialer_rejects_a_server_certificate_from_an_unrelated_ca);
    ("mTLS: the dialer's first bytes on the raw wire are a TLS handshake, not the preamble",
      `Quick, test_first_bytes_on_the_wire_are_a_tls_handshake);
    ("mTLS identity: a private key not matching its certificate is rejected at construction",
      `Quick, test_identity_rejects_a_key_that_does_not_match_its_certificate);
    ("mTLS identity: a certificate the trust anchor did not issue is rejected at construction",
      `Quick, test_identity_rejects_a_certificate_its_trust_anchor_did_not_issue);
    ("mTLS: the dial-side TLS handshake has a bounded timeout, not an unbounded hang", `Quick,
      test_dial_side_tls_handshake_has_a_bounded_timeout)
  ]
