defmodule RiptideWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :riptide

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_riptide_key",
    signing_salt: "PE9EIaAY",
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :riptide,
    gzip: not code_reloading?,
    only: RiptideWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint], log: false

  # Riptide has no CORS support otherwise — needed for any browser-based pod
  # client, which is inherently cross-origin from its pod by design (Solid/
  # LDP convention). No credentials (Riptide's own auth is a Bearer token in
  # a header, never a cookie), so a wildcard origin has no credential-leak
  # implication. Mounted before Plug.Parsers/the router so a preflight
  # OPTIONS request never reaches (and 404s from) route dispatch.
  plug CORSPlug,
    origin: "*",
    credentials: false,
    methods: ["GET", "PUT", "PATCH", "DELETE", "POST", "OPTIONS"],
    headers: ["Authorization", "Content-Type", "Last-Event-ID"]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  socket "/replication", RiptideWeb.Realtime.Socket, websocket: true, auth_token: true

  plug RiptideWeb.Router
end
