apiVersion: v1
kind: Service
metadata:
  name: riptide
  labels:
    app: riptide
spec:
  type: ClusterIP
  selector:
    app: riptide
  ports:
    - name: http
      port: 4000
      targetPort: 4000
    - name: metrics
      port: 9090
      targetPort: 9090
