import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :riptide, RiptideWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "yC4ZYgTNRajoqvMfeUp2kBQ0op+N4b7+7GsF3gdDxTjhmf64A5mgkdNMSdsGEKDF",
  watchers: []

# No real headless-service DNS exists on a developer's own machine — every
# ordinal resolves to whichever node is actually asking, exactly mirroring
# config/test.exs's own identical override (see its own comment for the
# full rationale). Without this, Riptide.RaCluster.default_ordinal_resolver/1
# falls through to real DNS (riptide-1.riptide-headless, etc.), which never
# resolves locally. Real Kubernetes deployments (config/runtime.exs) are
# untouched and keep using real DNS. A developer must still run with
# HOSTNAME set to one of the 3 fixed ordinals
# ("riptide-0"/"riptide-1"/"riptide-2") for
# Riptide.Application.placement_bootstrap_children/0's own separate gate to
# even attempt bootstrapping — this override alone isn't sufficient by
# itself, see the README's "Running locally for development" section. It
# is ALSO not sufficient on its own without Part B's fix below — see that
# section for why.
config :riptide, ordinal_resolver: fn _ordinal -> node() end

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :riptide, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
