(** The Key Encryption Key (KEK): the one long-lived, externally-supplied AES-256 key every
    per-record Data Encryption Key ({!Dek}) is wrapped under before it is stored in
    {!Redaction_store}'s keystore (design spec Decisions 4 and 5).

    {b Sourced from outside Riptide, never generated by it} (Decision 5). {!load} reads it from a
    permissions-restricted file produced by something else entirely ([openssl rand -out kek.bin
    32], a secrets manager's file mount, [age]/[sops], a Kubernetes Secret projected as a file) --
    the same shape [restic]'s master-key handling, [age]+[sops]'s file/env-var KEK pattern, and
    Kubernetes' own non-KMS encryption-provider baseline all use. A file is deliberately preferred
    over an environment variable, per OWASP's Cryptographic Storage Cheat Sheet's explicit caution
    about env-var key leakage through process listings, crash dumps, and logs. External
    KMS/Vault/HSM sourcing is a legitimate later upgrade, explicitly out of this spec's scope.

    {b Why this module does its own AES-GCM wrapping rather than reusing {!Dek.encrypt}.} The
    obvious implementation -- [Dek.encrypt (Dek.of_raw kek_bytes) dek_raw] -- is unsafe here, and
    {!Dek}'s own [.mli] says so in its "Concern for Task 6" note: every {!Dek.of_raw}
    reconstruction draws a fresh random 4-byte nonce prefix and resets its counter to zero, so a
    wrap performed through a freshly reconstructed [Dek.t] always encrypts under nonce
    [prefix || 0]. The nonce's entropy would therefore be the 32-bit prefix space alone, not the
    full 96-bit nonce space -- roughly {b 2^16 (~65,000)} wraps under one KEK before 50% odds of a
    nonce collision. A repeated GCM nonce under a repeated key is catastrophic, not degraded: it
    leaks the XOR of the two plaintexts (here, the XOR of two DEKs -- recover one, recover the
    other) and enables recovery of the GHASH authentication subkey, hence forgery. 65,000 records
    is nothing for an event-sourced log, so this is a live hazard at realistic volumes, not a
    theoretical one.

    {!Dek}'s deterministic counter nonce is the right construction for its own use case (one key,
    one message, NIST SP 800-38D §8.2.1) and the wrong one for this module's (one key, unboundedly
    many messages, across process restarts, with no place to durably carry counter state). This
    module therefore uses §8.2.2's other permitted construction instead -- an {b RBG-based} nonce:
    a fresh 96 bits from {!Mirage_crypto_rng}'s Fortuna CSPRNG per {!wrap}, giving a birthday bound
    of ~2^48 wraps rather than ~2^16. Same primitive ([Mirage_crypto.AES.GCM]), same standard,
    different permitted nonce construction, chosen to match this module's actual usage pattern. *)

type t
(** An AES-256 KEK. Holds raw key material; never serialize or log a [t]. *)

val of_raw : string -> t
(** [of_raw raw_bytes] builds a KEK from key material already in memory.

    Intended for tests and for callers that source key material through something other than a
    file ({!load} is the real, documented path for a deployment). Does not itself copy or lock
    memory.

    @raise Invalid_argument if [raw_bytes] is not exactly 32 bytes (256 bits) -- AES-256 only,
    unconditionally, matching {!Dek.of_raw}'s own refusal to silently accept a weaker key. *)

val load : path:string -> t
(** [load ~path] reads a KEK from the file at [path], which must contain {b exactly} 32 raw bytes
    (not hex, not base64, not a trailing newline -- [openssl rand -out kek.bin 32] produces exactly
    this) and must not be readable by group or other.

    Every failure mode raises rather than returning an option or falling back to a generated key:
    a process that cannot load its KEK must not start, because the alternative -- running with some
    other key -- silently makes every already-stored record permanently unrecoverable.

    @raise Sys_error if [path] does not exist or cannot be opened.
    @raise Invalid_argument if the file is not exactly 32 bytes long, or if its permission bits
    grant any access to group or other (Decision 5's "permissions-restricted file", checked rather
    than assumed: a world-readable KEK makes the entire redaction story decorative). *)

val wrap : t -> aad:string -> string -> string
(** [wrap t ~aad raw_dek] encrypts [raw_dek] (a {!Dek.raw} 32-byte DEK) under [t] with AES-256-GCM
    and a freshly generated 96-bit nonce (see this module's header for why a fresh random nonce,
    not a counter), returning the 12-byte nonce prepended to Mirage_crypto's own inline-tagged
    ciphertext. The nonce is not secret; it must travel with the wrapped key for {!unwrap} to
    recover it.

    [aad] is bound into the GCM tag as additional authenticated data and is {b not} stored in the
    output -- {!unwrap} must be given the same value. {!Redaction_store} passes the record's own
    [event_id], which binds each wrapped DEK to the exact keystore slot it belongs in: an attacker
    with write access to the keystore cannot move one record's wrapped DEK onto another record's
    key and have it authenticate. *)

val unwrap : t -> aad:string -> string -> string option
(** [unwrap t ~aad wrapped] splits off the leading 12-byte nonce, then authenticates and decrypts
    the remainder under [t] with [aad] as additional authenticated data.

    [None] if the input is shorter than the nonce, if GCM authentication fails (a wrong KEK, a
    wrong [aad], a tampered or corrupt keystore entry -- all indistinguishable, by design), or on
    any other failure. Never raises: an unreadable keystore entry is an ordinary, expected outcome
    on the redaction path, not an exceptional one. *)
